services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tcg_poc_web
      POSTGRES_USER: neimv
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
    command: server /data --console-address ":9001"

  # web:
  #   build:
  #     context: .
  #     dockerfile: dev.Dockerfile
  #   command: pipenv run python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - minio
  #   environment:
  #     DATABASE_URL: postgres://neimv:12345678@db/tcg_poc_web
  #     MINIO_URL: http://minio:9000
  #     MINIO_ACCESS_KEY: "minio"
  #     MINIO_SECRET_KEY: "minio123"