# Generated by Django 5.1.2 on 2024-11-07 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardProffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_k', models.CharField(default='0', max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('passive', models.TextField(blank=True)),
                ('active', models.TextField(blank=True)),
                ('quick_passive', models.TextField(blank=True)),
                ('quick_active', models.TextField(blank=True)),
                ('cost', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('attack', models.IntegerField(null=True)),
                ('rest', models.IntegerField(null=True)),
                ('banned', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/cards/')),
                ('approved', models.BooleanField(default=False)),
                ('kind', models.IntegerField(blank=True, null=True)),
                ('generation', models.IntegerField(blank=True, null=True)),
                ('element', models.IntegerField(blank=True, null=True)),
                ('original_deck', models.IntegerField(blank=True, null=True)),
                ('rarity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='uploads/file_cards/')),
                ('num_registers', models.IntegerField(blank=True, null=True)),
                ('num_ok', models.IntegerField(blank=True, null=True)),
                ('num_error', models.IntegerField(blank=True, null=True)),
                ('id_errors', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OriginalDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('name', models.CharField(default='normal', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('id_k', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('passive', models.TextField(blank=True)),
                ('active', models.TextField(blank=True)),
                ('quick_passive', models.TextField(blank=True)),
                ('quick_active', models.TextField(blank=True)),
                ('cost', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('rest', models.IntegerField(blank=True, null=True)),
                ('banned', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/cards/')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_card.element')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_card.generation')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_card.kind')),
                ('original_deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_card.originaldeck')),
                ('rarity', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_card.rarity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
