# Generated by Django 5.1.1 on 2024-09-25 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('name', models.CharField(default='normal', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_card.rarity'),
        ),
    ]
