# Generated by Django 5.1.1 on 2024-09-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_card', '0002_rarity_card_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecards',
            name='file',
            field=models.FileField(upload_to='uploads/file_cards/'),
        ),
    ]
