# Generated by Django 5.1.3 on 2024-11-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_card', '0002_load_data_from_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproffer',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_card.element'),
        ),
        migrations.AlterField(
            model_name='cardproffer',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_card.generation'),
        ),
        migrations.AlterField(
            model_name='cardproffer',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_card.kind'),
        ),
        migrations.AlterField(
            model_name='cardproffer',
            name='original_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_card.originaldeck'),
        ),
        migrations.AlterField(
            model_name='cardproffer',
            name='rarity',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_card.rarity'),
        ),
    ]
