# Generated by Django 5.1.1 on 2024-10-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_card', '0005_alter_filecards_num_error_alter_filecards_num_ok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/cards/'),
        ),
    ]
