# Generated by Django 5.1.1 on 2024-10-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_card', '0006_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='active',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='passive',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='quick_active',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='quick_passive',
            field=models.TextField(blank=True),
        ),
    ]
