# Generated by Django 5.1.1 on 2024-10-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_card', '0008_alter_card_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProffer',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('passive', models.TextField(blank=True)),
                ('active', models.TextField(blank=True)),
                ('quick_passive', models.TextField(blank=True)),
                ('quick_active', models.TextField(blank=True)),
                ('cost', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('attack', models.IntegerField(null=True)),
                ('rest', models.IntegerField(null=True)),
                ('banned', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/cards/')),
                ('kind', models.IntegerField(blank=True, null=True)),
                ('generation', models.IntegerField(blank=True, null=True)),
                ('element', models.IntegerField(blank=True, null=True)),
                ('original_deck', models.IntegerField(blank=True, null=True)),
                ('rarity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
