# Generated by Django 5.1.2 on 2024-10-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_card', '0010_cardproffer_approved_cardproffer_id_k_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='rest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
