# Generated by Django 5.1.2 on 2024-10-25 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_creator', '0001_initial'),
        ('user', '0002_create_initial_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cards_not_found',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.extendeduser'),
        ),
    ]
