# Generated by Django 5.1.2 on 2024-11-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_creator', '0002_remove_deck_cards_not_found_cardnotfound'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='valide_deck',
            field=models.BooleanField(default=False),
        ),
    ]
